### ISSUE TITLE
Testing on CItyscapes, the channels are wrong

### ISSUE THREAD

**Issue by Mbwslib** [AlexMa011/pytorch-polygon-rnn#8]
It is exciting to read this beautiful code. So I star it immediately. And I ran this code according to your steps. But Why am I getting this error?
Traceback (most recent call last):
  File "test.py", line 130, in <module>
    re = net.module.test(xx, 60)
  File "/home/mbw/poly1/pytorch-polygon-rnn-master/model.py", line 203, in test
    output1 = self.model1(input_data1)
  File "/home/mbw/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mbw/anaconda3/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/mbw/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mbw/anaconda3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight[64, 3, 3, 3], so expected input[1, 4, 224, 224] to have 3 channels, but got 4 channels instead

**Comment by AlexMa011** [comment]
It seems like a strange error since it indicates the input data have 4 channels. Could you please provide more information like the shape of I_obj and I in test.py? I really don't know why this would happen.

**Comment by AlexMa011** [comment]
It seems a PIL problem. I will try to push the new code soon.

**Comment by Mbwslib** [comment]
thanks，and I am looking forward to your new code.

**Comment by AlexMa011** [comment]
Sorry to reply late. I update the code and actually I didn't encounter the problem. Anyway, I make changes about converting the PIL loaded image to RGB. Hope it will solve your problem.

**Comment by Mbwslib** [comment]
I am very excited for this code, and I will try it as soon as possible.

**Comment by AlexMa011** [comment]
If you have no further problem, I will close this issue.
